#!/bin/sh

set -o nounset
set -o errexit

if [ "`whoami`" != "root" ]
then
    echo "You need to run as root!"
    exit 1
fi

: ${WISSBI_PID_DIR:="/var/run/wissbi"}
: ${WISSBI_LOG_DIR:="/var/log/wissbi"}
: ${WISSBI_META_DIR:="/var/lib/wissbi"}

start() {
    if pkill -0 wsbmetad.sh
    then
        echo "wsbmetad already started, stop first"
        exit 1
    fi
    /usr/bin/wsbmetad.sh &> $WISSBI_LOG_DIR/wsbmetad.log &
    echo "wsbmetad started"
}

stop() {
    pkill wsbmetad.sh
    echo "wsbmetad stopped"
}

restart() {
    stop
    start
}

status() {
    if pkill -0 wsbmetad.sh
    then
        echo "wsbmetad is running"
    else
        echo "wsbmetad is not running"
    fi
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
    ;;
esac
